### ISSUE TITLE
Undefined Type or Variable

### ISSUE THREAD

**Issue by etiennebrosse** [kb634/mondo-hawk#3]
Class Type does not seem to be know by hawk 

![mondoresult](https://cloud.githubusercontent.com/assets/5493501/10393660/0d84e6fe-6e92-11e5-9ac9-784b391b4fd7.png)

Event if all required metamodel seem to be there*

![listmetamodel](https://cloud.githubusercontent.com/assets/5493501/10393659/0d827e14-6e92-11e5-8f2f-f9679269ca94.png)
BTW org.eclise.uml metamodels were added thanks to the UML*.ecore file available on the ressources of the MDT/UML eclipse plugin.

**Comment by kb634** [comment]
I am unable to replicate this bug on my local copy (I make a new instance
run your query and just get 0 as a result, as expected).

The reason you are getting this error is (most likely) due to the fact you
have 2 uml metamodels registered to hawk. This means that the type "Class"
is not unique so hawk throws an exception letting you know you have 2 types
named "Class".

This can be resolved in 2 ways: either only have 1 type class in hawk (by
disabling the plugin which registers the duplicate version of uml).

Or prefix the query with the version of Class you wish to use (using the
NSURI of the metamodel you wish to use), for example:

return `http://www.eclipse.org/uml2/3.0.0/UML`::Class.all.size();
NB: the quotes used as the NSuri contains special characters

Let me know if this fixes it so the bug report can be closed.

Cheers,


On 9 October 2015 at 13:30, Etienne Brosse <notifications@github.com> wrote:

> Class Type does not seem to be know by hawk
>
> [image: mondoresult]
> <https://cloud.githubusercontent.com/assets/5493501/10393660/0d84e6fe-6e92-11e5-9ac9-784b391b4fd7.png>
>
> Event if all required metamodel seem to be there*
>
> [image: listmetamodel]
> <https://cloud.githubusercontent.com/assets/5493501/10393659/0d827e14-6e92-11e5-8f2f-f9679269ca94.png>
> BTW org.eclise.uml metamodels were added thanks to the UML*.ecore file
> available on the ressources of the MDT/UML eclipse plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kb634/mondo-hawk/issues/3>.
>



-- 
Konstantinos Barmpis | Research Student
White Rose Grid Enterprise Systems Group
Dept. of Computer Science
University of York
Tel: +44 (0) 1904-32 5653

Email Disclaimer:
http://www.york.ac.uk/docs/disclaimer/email.htm

**Comment by etiennebrosse** [comment]
You are right, it comes from to the fact that I have 2 UML metamodels. 
Prefixing the Class with its version seems to solve this.
Thanks
